#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xrdb
Version  : 1.1.0
Release  : 6
URL      : http://xorg.freedesktop.org/releases/individual/app/xrdb-1.1.0.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/app/xrdb-1.1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: xrdb-bin
Requires: xrdb-doc
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xmuu)
BuildRequires : pkgconfig(xproto)

%description
xrdb - X server resource database utility
All questions regarding this software should be directed at the
Xorg mailing list:

%package bin
Summary: bin components for the xrdb package.
Group: Binaries

%description bin
bin components for the xrdb package.


%package doc
Summary: doc components for the xrdb package.
Group: Documentation

%description doc
doc components for the xrdb package.


%prep
%setup -q -n xrdb-1.1.0

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xrdb

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
