#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xrdb
Version  : 1.1.1
Release  : 9
URL      : http://xorg.freedesktop.org/releases/individual/app/xrdb-1.1.1.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/app/xrdb-1.1.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT MIT-Opengroup
Requires: xrdb-bin
Requires: xrdb-doc
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xmuu)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
xrdb - X server resource database utility
All questions regarding this software should be directed at the
Xorg mailing list:

%package bin
Summary: bin components for the xrdb package.
Group: Binaries

%description bin
bin components for the xrdb package.


%package doc
Summary: doc components for the xrdb package.
Group: Documentation

%description doc
doc components for the xrdb package.


%prep
%setup -q -n xrdb-1.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1522111616
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1522111616
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xrdb

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
