#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : xrdb
Version  : 1.2.0
Release  : 13
URL      : http://xorg.freedesktop.org/releases/individual/app/xrdb-1.2.0.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/app/xrdb-1.2.0.tar.gz
Source99 : http://xorg.freedesktop.org/releases/individual/app/xrdb-1.2.0.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT MIT-Opengroup
Requires: xrdb-bin = %{version}-%{release}
Requires: xrdb-license = %{version}-%{release}
Requires: xrdb-man = %{version}-%{release}
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xmuu)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
xrdb - X server resource database utility
-----------------------------------------

%package bin
Summary: bin components for the xrdb package.
Group: Binaries
Requires: xrdb-license = %{version}-%{release}

%description bin
bin components for the xrdb package.


%package license
Summary: license components for the xrdb package.
Group: Default

%description license
license components for the xrdb package.


%package man
Summary: man components for the xrdb package.
Group: Default

%description man
man components for the xrdb package.


%prep
%setup -q -n xrdb-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557106730
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1557106730
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xrdb
cp COPYING %{buildroot}/usr/share/package-licenses/xrdb/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xrdb

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xrdb/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xrdb.1
